name: life_manager_app
description: Application de gestion de vie étudiante avec thèmes My Hero Academia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  timezone: ^0.9.0
  
  flutter_local_notifications: ^17.0.0

  # Base de données
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Gestion d'état
  provider: ^6.1.1
  
  # UI
  intl: ^0.19.0
  fl_chart: ^0.69.0
  
  # Stockage sécurisé
  shared_preferences: ^2.2.2

    # Images
  image_picker: ^1.0.7  # AJOUTE CETTE LIGNE
  path_provider: ^2.1.2  # AJOUTE CETTE LIGNE
  
  # Retire cette ligne temporairement
  # flutter_local_notifications: ^16.3.0
  
  # Icônes
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
